### ISSUE TITLE
Gettings this in every csv try - got an unexpected keyword argument 'error_bad_lines'

### ISSUE THREAD

**Issue by Greatz08** [simonw/csvs-to-sqlite#99]
![20240126_14h44m29s_grim](https://github.com/simonw/csvs-to-sqlite/assets/55040435/45727ef4-29b5-494f-8981-4688fef944cf)

**Comment by neiltron** [comment]
The fix seems to be to rollback pandas to a previous version. [This thread](https://github.com/simonw/csvs-to-sqlite/issues/88) mentions pinning to 1.4.0.

**Comment by segv** [comment]
I fixed this error locally but then hit another pandas-api-has-changed error:

```
Traceback (most recent call last):
  File ".../.pyenv/versions/zen312/bin/csvs-to-sqlite", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File ".../.pyenv/versions/3.12.2/envs/zen312/lib/python3.12/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.pyenv/versions/3.12.2/envs/zen312/lib/python3.12/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File ".../.pyenv/versions/3.12.2/envs/zen312/lib/python3.12/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.pyenv/versions/3.12.2/envs/zen312/lib/python3.12/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../csvs-to-sqlite/csvs_to_sqlite/cli.py", line 253, in cli
    to_sql_with_foreign_keys(
  File "/home/mb/z/datasets/csvs-to-sqlite/csvs_to_sqlite/utils.py", line 357, in to_sql_with_foreign_keys
    create_sql, columns = get_create_table_sql(
                          ^^^^^^^^^^^^^^^^^^^^^
  File ".../csvs-to-sqlite/csvs_to_sqlite/utils.py", line 314, in get_create_table_sql
    columns_and_types = df.dtypes.iteritems()
                        ^^^^^^^^^^^^^^^^^^^
  File ".../.pyenv/versions/3.12.2/envs/zen312/lib/python3.12/site-packages/pandas/core/generic.py", line 6296, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The datasetter intro and getting started docs suggest using csvs-to-sqlite via `pip install csvs-to-sqlite`, which doesn't work if being run in a clean virtualenv (since latests pandas doesn't work with latest csvs-to-sqlite and the docs don't say to pin pandas).

I'm more than happy to have a try at making csvs-to-sqlite support both old and new pandas (how hard can it be :) ) but is there a plan to move away from old pandas or is the idea to stick with 1.4?

**Comment by kshychko** [comment]
Python 3.9 and pinning pandas and numpy versions pin helped:
```
pip install csvs-to-sqlite pandas==1.4.0 numpy==1.26.4
```

**Comment by medul6** [comment]
@kshychko thanks, that worked, but I had to specify python 3.10

**Comment by simonw** [comment]
Finally fixed, the fix is going out in a release shortly.
